services:
  postgres:
    image: postgres:16-alpine
    container_name: animascotas-db
    environment:
      POSTGRES_DB: animascotas
      POSTGRES_USER: animascotas_user
      POSTGRES_PASSWORD: animascotas_pass
    ports:
      - "5432:5432"
    volumes:
      - animascotas_data:/var/lib/postgresql/data

volumes:
  animascotas_data: